[versions]
spring-dependency-management = "1.1.4"
arquillian-bom = "1.1.13.Final"
javaee-api = "7.0"
junit = "4.12"
arquillian-weld = "1.0.0.CR9"
weld-core = "2.4.2.SP1"
slf4j = "1.7.25"
pmd = "6.55.0"

[libraries]
javaee-api = { module = "javax:javaee-api", version.ref = "javaee-api" }
junit = { module = "junit:junit", version.ref = "junit" }
arquillian-bom = { module = "org.jboss.arquillian:arquillian-bom", version.ref = "arquillian-bom" }
arquillian-junit = { module = "org.jboss.arquillian.junit:arquillian-junit-container" }
arquillian-weld-embedded = { module = "org.jboss.arquillian.container:arquillian-weld-ee-embedded-1.1", version.ref = "arquillian-weld" }
weld-core = { module = "org.jboss.weld:weld-core", version.ref = "weld-core" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
